image: node:alpine

stages:
    - build
    - deploy
    
variables:
  AWS_DEFAULT_REGION: us-east-2   # The region of our S3 bucket
  BUCKET_NAME: profiles.kenzie.academy   # Your bucket name
  AWS_ACCESS_KEY_ID: AKIASY73XR2M2TUI7IEL
  AWS_SECRET_ACCESS_KEY: /s5qCvHr6jjzB8E/yYfbOHARV586EpvV53x+VUpC
  
cache:
  paths:
  - node_modules
  
build site:
    stage: build
    script:
        - echo "Building"
        - npm install
        - npm run build --prod
        - echo "Build Successful"
    artifacts:
        paths:
            - build/
    
deploy to s3:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync build/ s3://profiles.kenzie.academy --exclude ".DS_Store/*" --cache-control "max-age=120000" --delete
  only:
    - master # Only run on master branch