image: srikoushik/aws-cli-node-docker

stages:
    - build
    - deploy
    
variables:
  AWS_DEFAULT_REGION: us-east-2   # The region of our S3 bucket
  BUCKET_NAME: profiles.kenzie.academy   # Your bucket name
  
cache:
  paths:
  - node_modules
  
build site:
    stage: build
    script:
        - echo "Building"
        - npm install
        - npm run build --prod
        - echo "Build Successful"
    artifacts:
        paths:
            - build/
    
deploy to s3:
  stage: deploy
  script:
    - sh sync.sh
  only:
    - master # Only run on master branch